import numpy as np
import torch
import os
from scipy.spatial import cKDTree

class LidarSensor:
    def __init__(self, ray_file_path: str, num_envs: int, device: torch.device, num_output_rays: int = 60):
        """
        Args:
            ray_file_path: Path to the .npz file generated by track_rays.py
            num_envs: Number of environments
            device: torch device
            num_output_rays: How many rays to return in the observation (default 20).
                             This determines the downsampling stride.
        """
        self.device = device
        self.num_envs = num_envs
        self.num_output_rays = num_output_rays

        # "racing_env/envs/sensors/lidar_scans/" + ray_file_path + ".npz"
        path = os.path.join(os.path.dirname(__file__), "lidar_scans", ray_file_path + ".npz")
        
        if not os.path.exists(path):
            raise FileNotFoundError(f"Lidar ray file not found: {path}")
            
        print(f"Loading Lidar map from {ray_file_path}...")
        data = np.load(path, allow_pickle=True)
        
        # coords_m: (N, 2) metric coordinates of free pixels
        self.coords_m = data['coords_m']
        # rays_m: (N, K) ray lengths
        self.rays_m = torch.tensor(data['rays_m'], dtype=torch.float32, device=device)
        self.angle_step = float(data['meta'].item()['angle_step_deg'])
        self.total_rays = self.rays_m.shape[1]
        
        # Calculate stride to downsample to the requested number of rays
        # e.g., if total=360 and output=20, stride=18
        self.ray_stride = max(1, self.total_rays // self.num_output_rays)

        # Build KDTree for fast lookup
        # Note: KDTree runs on CPU, we query it with numpy, then move results to GPU
        self.tree = cKDTree(self.coords_m)
        
        print(f"Lidar initialized: {self.coords_m.shape[0]} points. "
              f"Source: {self.total_rays} rays. Output: {self.num_output_rays} rays (stride: {self.ray_stride}).")

    def get_observation(self, x: torch.Tensor, y: torch.Tensor, yaw: torch.Tensor):
        """
        Get lidar ranges for a batch of vehicles.
        
        Args:
            x, y: (num_envs,) Vehicle position
            yaw: (num_envs,) Vehicle heading in radians
            
        Returns:
            lidar_ranges: (num_envs, num_output_rays) ego-centric ray lengths
        """
        # 1. Find nearest pre-computed point
        # Move query points to CPU for KDTree
        query_points = torch.stack([x, y], dim=1).cpu().numpy()
        
        # Query nearest neighbor (k=1)
        _, indices = self.tree.query(query_points)
        
        # 2. Retrieve global rays for these points
        # indices is (num_envs,), use it to select rows from rays_m
        indices_torch = torch.tensor(indices, device=self.device, dtype=torch.long)
        global_rays = self.rays_m[indices_torch] # (num_envs, total_rays)
        
        # 3. Rotate rays to be ego-centric
        # Convert yaw to index shift
        yaw_deg = torch.rad2deg(yaw) % 360.0
        # Calculate how many steps we need to shift
        shifts = (yaw_deg / self.angle_step).round().long()
        
        # 4. Create a sparse grid of indices to gather
        # Instead of arange(total_rays), we use arange(0, total_rays, stride)
        # to select only the specific 20 rays we want.
        base_indices = torch.arange(0, self.total_rays, self.ray_stride, device=self.device).unsqueeze(0).repeat(self.num_envs, 1)
        
        # Add shift (unsqueeze to broadcast: (num_envs, 1) + (num_envs, num_output_rays))
        gather_indices = (base_indices - shifts.unsqueeze(1)) % self.total_rays
        
        # Gather the values
        # Output shape will be (num_envs, num_output_rays)
        ego_rays = torch.gather(global_rays, 1, gather_indices)
        
        return ego_rays