- name: "vx"
  dim: 1
  min_val: 0
  max_val: 20
  rand: 0.05

- name: "r"
  dim: 1
  min_val: -5
  max_val: 5
  rand: 0.05

- name: "heading_diff"
  dim: 1
  min_val: -3.141592653589793
  max_val: 3.141592653589793
  rand: 0.05

- name: "closest_dist"
  dim: 1
  min_val: -3
  max_val: 3

- name: "delta_ref_history"
  dim: 1
  min_val: -0.5
  max_val: 0.5

- name: "omega_wheels_ref"
  dim: 1
  min_val: 0
  max_val: 5

- name: "dist_to_edge"
  dim: 1
  min_val: -1
  max_val: 1

- name: "omega_wheels"
  dim: 1
  min_val: 0
  max_val: 10

- name: "curvatures"
  dim: 20
  min_val: -3.141592653589793
  max_val: 3.141592653589793
  length: 60
  sample_rate: 3