- name: "vx"
  dim: 1
  min_val: 0
  max_val: 20
  rand: 0.05

- name: "vy"
  dim: 1
  min_val: -10
  max_val: 10
  rand: 0.05

- name: "r"
  dim: 1
  min_val: -5
  max_val: 5
  rand: 0.05

- name: "delta_history"
  dim: 1
  min_val: -0.4
  max_val: 0.4

- name: "delta_ref_history"
  dim: 1
  min_val: -0.4
  max_val: 0.4

- name: "omega_dot_history"
  dim: 1
  min_val: -75
  max_val: 75

- name: "omega_wheels"
  dim: 1
  min_val: 0
  max_val: 10

- name: "omega_wheels_ref"
  dim: 1
  min_val: 0
  max_val: 10

- name: "heading_diff"
  dim: 1
  min_val: -3.141592653589793
  max_val: 3.141592653589793
  rand: 0.05

- name: "closest_dist"
  dim: 1
  min_val: -3
  max_val: 3

- name: "progres_sin"
  dim: 1
  min_val: -1
  max_val: 1

- name: "progres_cos"
  dim: 1
  min_val: -1
  max_val: 1

- name: "friction"
  dim: 7
  min_val: 0
  max_val: 2
  length: 70
  sample_rate: 10
